### ISSUE TITLE
Request to Add Product in Start Flutter

### ISSUE THREAD

**Issue by maheshwari-1153** [OmarHatem28/yala_mazzad#3]
Hello,

I am Maheshwari from team [GeekyAnts](https://geekyants.com/). On behalf of [Start Flutter](https://startflutter.com/), we add open source products which we find helpful to the community & also we provide credits to author itself.

Let me know if you are interested showcase your product in our open source website.

If yes, then I request you to add MIT Licence in your repo.

Looking forward to hear from you.

**Comment by OmarHatem28** [comment]
Greetings Maheshwari,

Sure thing, I've added the MIT License to the repo, you can go ahead and add it to your website.
Also could you kindly notify me via email when you add it.
My email: omarh.ismail1@gmail.com

Thanks in advance for your time,
Best regards.

**Comment by maheshwari-1153** [comment]
Sure, will let you know when we add.

Thanks,
Maheshwari
